version: "3"

services:
  mutant-api:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./logs:/usr/src/api/logs
    depends_on:
      - mutant-db

  mutant-db:
    image: mysql:5.7
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_mutant
    command: --innodb-use-native-aio=0
