server:
  host: localhost
  port: 3000
  prefix: api/v1

jsonplaceholder:
  baseURL: https://jsonplaceholder.typicode.com
  timeout: 30000
  maxRedirects: 5

swagger:
  title: Mutant - Desafio NodeJS
  description: API de consulta de usuários
  version: 0.0.1
  prefix: api/doc

db:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  database: db_mutant
  charset: utf8mb4
  synchronize: true
  logging: false
